name: Branches

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: docker-compose up -d
    - run: docker run --network container:kms appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
    - run: yarn test
      env:
        CI: true
        NODE_ENV: test
